### ISSUE TITLE
UI: link to docs

### ISSUE THREAD

**Issue by meghanhade** [mapzen/mobility-explorer#112]

**Comment by drewda** [comment]
@rmglennon will provide example URLs (which will only work after production doc deploy)

**Comment by rmglennon** [comment]
For the current ? buttons:

General Mobility Explorer home: https://mapzen.com/documentation/mobility/explorer/explore-transit

Routes: https://mapzen.com/documentation/mobility/explorer/explore-transit/#explore-transit-routes

Isochrones from Mobility Explorer: https://mapzen.com/documentation/mobility/explorer/isochrones/
