### ISSUE TITLE
isochrone not rendering correctly

### ISSUE THREAD

**Issue by meghanhade** [mapzen/mobility-explorer#163]
rings aren't rendering.

**Comment by drewda** [comment]
@meghanhade here are some notes for when you're ready to try @kevinkreiser's TurfJS code within Mobility Explorer:
1. add [Ember Browserify](https://github.com/ef4/ember-browserify), which will allow you to access NPM packages within Ember client-side code:  `npm install --save-dev ember-browserify`
2. install whatever [Turf NPM packages](https://www.npmjs.com/package/turf#functions) you need. For example: `npm install turf-centroid --save-dev`
3. import the specific Turf module wherever you need it. Here's an example of how I used the Turf's centroid function in the Feed Registry: https://github.com/transitland/feed-registry/blob/0718af67e68abf6e56b48348e187a518851de851/app/operator/model.js#L4
