### ISSUE TITLE
hover route not always selecting correct route

### ISSUE THREAD

**Issue by meghanhade** [mapzen/mobility-explorer#164]
it sometimes seems to want to select a few routes out of many

**Comment by drewda** [comment]
Perhaps upgrading to Leaflet 1.0 and the latest version of Ember Leaflet will help with this? (That said, I'm not sure if either of those newer versions introduce other breaking changes.)

**Comment by meghanhade** [comment]
Can't reproduce ¯_(ツ)_/¯

**Comment by meghanhade** [comment]
reproduced: happens when viewing routes with an operated_by parameter present
