### ISSUE TITLE
Add skinning to make Explorer fit on mapzen.com

### ISSUE THREAD

**Issue by rmglennon** [mapzen/mobility-explorer#181]
If we put the Mobility Explorer on mapzen.com, it'll need a banner/header/footer/etc. Products folks can help with this.

Similar to the Metro Extracts site: https://mapzen.com/data/metro-extracts/

cc @migurski

**Comment by migurski** [comment]
The super-simple version of this is to use [CSS & JS from the Styleguide](https://mapzen.com/common/styleguide/), and then dynamically include these two HTML blocks to keep up to date with navigation changes:
- https://mapzen.com/site-fragments/navbar.html
- https://mapzen.com/site-fragments/footer.html

I can help with more detail!
