### ISSUE TITLE
enable previews of feature branches using Precog

### ISSUE THREAD

**Issue by drewda** [mapzen/mobility-explorer#194]
At present, the contents of the master branch are built and deployed to the dev server. Sharing work-in-progress would be even easier if we can set up Mobility Explorer with Precog. That would allow us to preview and share feature branches, before merging in to master.

TODO:
- [x] set up artifact generation on CircleCI: https://github.com/mapzen/precog/blob/master/README.md#basic-usage
- [x] build the app assets on every run of CircleCI (not just on master and production branch pushes)
- [x] Precog and Ember both massage URLs. Some untangling may be required to help them play nicely with each other.

Related: https://github.com/transitland/feed-registry/issues/330

//cc @migurski @meghanhade

**Comment by drewda** [comment]
Seems to work: https://precog.mapzen.com/mapzen/mobility-explorer/precog/ !

I was expecting to run into problems with URL manipulation. That's a blocker on https://github.com/transitland/feed-registry/issues/330, where Precog doesn't play nicely with Ember's use of the HTML5 History API for client-side routing: https://guides.emberjs.com/v2.9.0/configuring-ember/specifying-url-type/#toc_history

But in Mobility Explorer, we're using plain, old hash-style routing: https://guides.emberjs.com/v2.9.0/configuring-ember/specifying-url-type/#toc_hash No conflicts between Precog and Ember in that case.

@meghanhade ready for you to merge whenever you'd like to enable Precog.

@migurski if the combo of Precog + HTML5 History API is intriguing, glad to look at it more all together--but it's not pressing.

**Comment by migurski** [comment]
Looks 👍 to me.
