### ISSUE TITLE
Add a sentence about what Mobility Explorer does

### ISSUE THREAD

**Issue by rmglennon** [mapzen/mobility-explorer#200]
OK, here's a start to a sentence for the top of the page...let's refine and discuss in comments!

Mobility Explorer helps you learn about multimodal transportation in your area. Search for a place or browse the map, and use the buttons to ask questions about transit routes, stops, and operators. Mobility Explorer integrates open transit data from Transitland and transportation inquiry services from Mapzen.

**Comment by drewda** [comment]
Riffing on what you've started @rmglennon (with brackets around what could be links out): 

> There are so many ways to get from A to B! Use Mapzen Mobility Explorer to understand transportation networks around the world. Search for a place using [Mapzen Search] or browse the map. Use the buttons below to construct queries.
> 
> Mass-transit data comes from [Transitland]. Pedestrian, bicycle, and auto data comes from [OpenStreetMap]. Analysis is powered by [Mapzen Mobility services].

**Comment by meghanhade** [comment]
Add a way to close this component.
A service should track whether this component has been closed.
