### ISSUE TITLE
How to go back after looking at item details

### ISSUE THREAD

**Issue by rmglennon** [mapzen/mobility-explorer#226]
I'm not sure how to explain this, but I keep finding that I'm missing a way to go back to my previous query and map extent after getting into the details of a selected item.

How to reproduce:

1. Navigate to an area of interest.
2. Click Routes to view the routes in this area. (You can also do this with the other options.)
3. Click an individual route on the map. The sidebar updates to show details about the selected route and give commands for stops and route stop patterns. If you just hover over a route, the details and the Style routes by commands are both shown.

Now, I want to return to the previous map where all the routes were shown so I can look at the details of another route, so I'm looking for a back button or a close icon here in the details. 

I believe the way to do this is to click Routes again, although I didn't think of that immediately, or possibly the Back button on the browser. Because the whole site "feels" like one entity, you might not expect individual queries to be added to the browser history. Going back to @migurski's thought, perhaps adding verbs to the section headings (Show routes?) would make people remember that that's what they clicked to get into the query mode in the first place?

![image](https://cloud.githubusercontent.com/assets/4380498/20078899/3d2679e4-a4f7-11e6-99f1-97fd8af458ec.png)

**Comment by meghanhade** [comment]
@rmglennon Yep,  the way to navigate back is to use the back button. The stateful URL is a big part of the explorer, allowing people to share exactly what they were looking at (in nearly all cases). I'm not sure how to best highlight this feature, but I'd guess it might be something people catch onto after trying the back button?

**Comment by meghanhade** [comment]
@rmglennon re: using verbs--yes! I did put that in after @migurski suggested that, but it didn't make out of that branch yet. I'll add them and you can see if it matches what you're thinking.

**Comment by rmglennon** [comment]
Thanks @meghanhade! I'll work on documenting this workflow and highlight that the URL is its own query with a back/forward state.
