### ISSUE TITLE
Map Matching - indicate that the samples are samples

### ISSUE THREAD

**Issue by rmglennon** [mapzen/mobility-explorer#387]
To make it clearer that the sample GPX files are text examples, let's append Sample: or something like that to their name in the drop-down list.

Sample: route description
Sample: San Francisco half-marathon run

**Comment by meghanhade** [comment]
@rmglennon do you think we need to do this even with the title over the drop down that says "sample gpx traces"? Also, the placeholder text for the drop-down select also says "select a sample gpx trace...".

**Comment by rmglennon** [comment]
hey @meghanhade! The reason I was thinking this is because we've moved the UI to launch the uploader into the drop-down list, and we might want to call the list something generic to reflect that it does both the sample and the upload part.

**Comment by rmglennon** [comment]
Maybe something like (also in #327) this? Let's chat about it!

Heading above the drop-down for Sample GPX trace --> Choose a GPX trace

Drop-down list text for Select a sample GPX trace... --> either no text or default to the first entry in the list.

**Comment by rmglennon** [comment]
We modified the copy in other ways to indicate these are samples.
