### ISSUE TITLE
Total number of operators does not update when redoing search in new area

### ISSUE THREAD

**Issue by rmglennon** [mapzen/mobility-explorer#410]
Minor issue with the caption on the Operators list. 

To reproduce:

1. Search for Oakland, California.
2. Click Show Operators. The caption on the drop-down list says "7 operators".
3. Zoom out to see the whole Bay Area. 
4. Click Redo search.
5. The map updates to show many more operators, but the drop-down list still says "7 operators". All the individual operators (there are about 40) are in the list.

![image](https://cloud.githubusercontent.com/assets/4380498/25690659/4f571e3e-3048-11e7-9855-b05676c6825c.png)

**Comment by meghanhade** [comment]
Thanks for noticing this, @rmglennon!
