### ISSUE TITLE
Include/exclude isochrones with BART affects ferry route options

### ISSUE THREAD

**Issue by rmglennon** [mapzen/mobility-explorer#413]
I'm looking at include/exclude operators and routes, and am finding some interesting behavior regarding BART.

Here's all transit from Oakland during a weekday morning commute hours:

![image](https://cloud.githubusercontent.com/assets/4380498/25734948/6a352794-311c-11e7-980d-cf6ff67664f6.png)

Here's when I exclude BART. It looks like BART is the operator for all the ferries in this area because they disappear from the map. Similarly, if you include only BART, you get some ferry routes.

![image](https://cloud.githubusercontent.com/assets/4380498/25734997/ea8a31b4-311c-11e7-8266-6ce06811fd9b.png)

Perhaps something is strange with the `use_ferries` value of 0 here, which is an attempt to avoid ferries. (The API default is 0.5) I'm still investigating this, but wanted to get started on an issue somewhere.

**Comment by meghanhade** [comment]
@rmglennon can we close this issue now?

**Comment by rmglennon** [comment]
Yes, issues were with the service.
