### ISSUE TITLE
Search box: Include locality (city) in autocomplete list

### ISSUE THREAD

**Issue by rmglennon** [mapzen/mobility-explorer#421]
The search autocomplete does not include the `locality` (the city) in the list. This makes it hard to find the right location if there are multiple addresses within the same `region` (the state). 

To reproduce:
1. Zoom to the Bay Area and start typing 2201 Broadway.
2. You get two results. It turns out one is near Sacramento, and the other is in Oakland.
3. You have to type Oakland completely to make sure you get the one in Oakland, but the autocomplete doesn't update to show the `locality` as Oakland.

![image](https://cloud.githubusercontent.com/assets/4380498/26071723/e56cbfaa-395d-11e7-9518-62b42ad52d3c.png)

I'm sure there are reasons for why we built it like this, so just adding this here as an enhancement.

**Comment by drewda** [comment]
Yes, this is confusing as-is. It should be straightforward to add locality to every place the search results are rendered. For instance: https://github.com/mapzen/mobility-explorer/blob/722003294e2d66691f23a4153d6bd94a80b6e241/app/route-stop-patterns/template.hbs#L105
