### ISSUE TITLE
Make a plan for Mobility API links that rely on keyless access

### ISSUE THREAD

**Issue by rmglennon** [mapzen/mobility-explorer#427]
The section of Mobility Explorer that uses Mobility APIs (isochrones + map-matching, eventually) has a link for `See the Mapzen Mobility API request for these results`. 

These links are going to open to an error message when keyless access ends (currently, targeting by June 1). The error will indicate that a Mapzen API key is needed, which could be jarring and unexpected for most users.

We need to come up with how to handle these... 
- Now, append a working key here? 
- Later, do some fancy swapping stuff? Show the URL query in a pop-up (as the structure is likely more useful than the raw JSON response)?

cc @rfriberg @meghanhade

**Comment by drewda** [comment]
Sounds like we should have something in place on production by the end of this week.

**Comment by meghanhade** [comment]
Plan (per discussion w/ @rfriberg):  use company-account keys that are unique for Explorer.
