### ISSUE TITLE
when displaying one route, no need to show "redo search in map area" button

### ISSUE THREAD

**Issue by drewda** [mapzen/mobility-explorer#445]
Steps to reproduce:

1. View a route. For example: https://mapzen.com/mobility/explorer/#/routes?bbox=-122.42610454559325%2C37.78167112478022%2C-122.37688064575197%2C37.81086891407298&onestop_id=r-9q8zn-powell~mason
2. Move the map
3. The red "redo search in map area" button appears

Pressing the button and redoing the search won't yield different results. It's still the same route Onestop ID going in to the API; the difference in bounding box doesn't matter.

So, we should disable the button from appearing on bbox change in this view.

(Of course, assuming I'm not forgetting about some other intended functionality!)

**Comment by meghanhade** [comment]
Thanks @drewda, you're right--there's no need for this button when viewing an individual route!
