### ISSUE TITLE
Add support for multiple locations in an isochrone search

### ISSUE THREAD

**Issue by stevevance** [mapzen/mobility-explorer#516]
I've built a tool called "Zoning Assessment" that measures the geographic area of the different zoning districts, and symbolizes by their classification (R-Residential, B-Business, etc.) [within a 10 minute walk shed of Chicago Transit Authority stations](https://www.chicagocityscape.com/zoning.php?place=ctastation-wilson&radius=1320). 

Currently, the Isochrone API can only handle a single location. 

However, Chicago has a transit-oriented development law that changes the zoning rules for properties within a certain distance of a CTA station **entrance**. 

I would like to provide the isochrone service all three station entrances for the Wilson station. 

Without knowing that the isochrone API accepted only 1 location I tried this API call:
````
https://matrix.mapzen.com/isochrone?api_key=search-zN8_XgQ&json=%7B%22locations%22%3A%5B%0A%7B%22lon%22%3A-87.6580399%2C+%22lat%22%3A41.9655093%7D%2C%0A%7B%22lon%22%3A-87.657989%2C%22lat%22%3A41.965262%7D%2C%0A%7B%22lon%22%3A-87.6574901%2C%22lat%22%3A41.9635788%7D%0A%5D%2C+%22costing%22%3A%22pedestrian%22%2C%22contours%22%3A+%5B%7B%22time%22%3A10%2C%22color%22%3A%22ff0000%22%7D%5D%2C+%22polygons%22%3A+true%7D
````

The JSON payload looks like this:
````
{
  "locations": [
    {
      "lon": -87.6580399,
      "lat": 41.9655093
    },
    {
      "lon": -87.657989,
      "lat": 41.965262
    },
    {
      "lon": -87.6574901,
      "lat": 41.9635788
    }
  ],
  "costing": "pedestrian",
  "contours": [
    {
      "time": 10,
      "color": "ff0000"
    }
  ],
  "polygons": true
}
````

The error message I got:
````
{
  "error_code": 150,
  "error": "Exceeded max locations:1",
  "status_code": 400,
  "status": "Bad Request"
}
````

**Comment by rmglennon** [comment]
Hey @stevevance -- there was some work done to support multiple points in an isochrone, though it is not yet exposed in the Mapzen-hosted API.

https://github.com/valhalla/valhalla/issues/452
