### ISSUE TITLE
feature suggestion: link to openstreetmap.org for more info on ways

### ISSUE THREAD

**Issue by drewda** [mapzen/mobility-explorer#79]
@meghanhade an idea to consider: for more information about an OSM way, link to `https://openstreetmap.org/way/xxxxx`

![openstreetmap way california drive 417976722 2016-07-18 10-08-00](https://cloud.githubusercontent.com/assets/212369/16923635/135f36ca-4cd0-11e6-93d4-7aa41267913d.png)

**Comment by meghanhade** [comment]
@drewda great idea, thanks
