### ISSUE TITLE
leaflet bbox sometimes gets set to incorrect value

### ISSUE THREAD

**Issue by meghanhade** [mapzen/mobility-explorer#81]
It sometimes sets to a location in antarctica. Not able to consistently reproduce error.

**Comment by meghanhade** [comment]
This does not happen when using bbox in a link-to rather than leafletBbox. When transitioning/linking to new route, the leafletBbox does not always get passed properly.

**Comment by meghanhade** [comment]
This PR fixed some bbox issues: https://github.com/mapzen/mobility-explorer/pull/83. (TBD if remaining bbox issues exist)

**Comment by irees** [comment]
It looks like `bbox` coordinates passed into links are being flipped at some point.

Before going to Antarctica:

`["-122.41137385368347", "37.65657696792479", "-122.39368200302124", "37.66507035959997"]
`

After going to Antarctica:

`["37.65657696792479", "-122.41137385368347", "37.66507035959997", "-122.39368200302124"]`

when generating a link, e.g.:

``````
{{#link-to 'routes' (query-params bbox=bbox onestop_id=null serves=null operated_by=onestop_id  served_by=null style_routes_by=null) }}View routes served by this operator{{/link-to}}```
``````
